add periodic s390x cross-build nightly job. (#3474)
Signed-off-by: Vamsi Krishna Siddu <vamsikrishna.siddu@ibm.com>

diff --git a/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml b/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
--- a/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
+++ b/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
@@ -360,6 +360,80 @@ periodics:
       type: bare-metal-external
 - annotations:
     testgrid-create-test-group: "false"
+  cluster: kubevirt-prow-workloads
+  cron: 2 1 * * *
+  decorate: true
+  decoration_config:
+    grace_period: 5m0s
+    timeout: 1h0m0s
+  extra_refs:
+  - base_ref: main
+    org: kubevirt
+    repo: kubevirt
+  labels:
+    preset-docker-mirror-proxy: "true"
+    preset-gcs-credentials: "true"
+    preset-kubevirtci-quay-credential: "true"
+    preset-podman-in-container-enabled: "true"
+    preset-shared-images: "true"
+  max_concurrency: 1
+  name: periodic-kubevirt-push-nightly-build-main-s390x
+  spec:
+    containers:
+    - command:
+      - /usr/local/bin/runner.sh
+      - /bin/sh
+      - -c
+      - |
+        set -e
+        build_date="$(date +%Y%m%d)"
+        cat "$QUAY_PASSWORD" | podman login --username $(cat "$QUAY_USER") --password-stdin=true quay.io
+        export DOCKER_TAG="${build_date}_$(git show -s --format=%h)-s390x"
+        make
+        counter=3
+        retval=0
+        while [ $counter -gt 0 ]; do
+            set +e
+            make push
+            retval=$?
+            set -e
+            if [ $retval -eq 0 ]; then
+                break
+            fi
+            set +e
+            counter=$(expr $counter - 1)
+            set -e
+            sleep 120
+        done
+        if [ $retval -ne 0 ]; then
+            echo "push failed!"
+            exit 1
+        fi
+        # build functest currently does not support crossbuild, skip it
+        git show -s --format=%H > _out/commit
+        echo ${build_date} > _out/build_date
+        bucket_dir="kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${build_date}"
+        gsutil cp ./_out/manifests/release/kubevirt-operator.yaml gs://$bucket_dir/kubevirt-operator-s390x.yaml
+        gsutil cp ./_out/manifests/release/kubevirt-cr.yaml gs://$bucket_dir/kubevirt-cr-s390x.yaml
+        gsutil cp -r ./_out/manifests/testing gs://$bucket_dir/testing-s390x
+        gsutil cp ./_out/commit gs://$bucket_dir/commit-s390x
+        gsutil cp ./_out/build_date gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest-s390x
+      env:
+      - name: DOCKER_PREFIX
+        value: quay.io/kubevirt
+      - name: BUILD_ARCH
+        value: crossbuild-s390x
+      image: quay.io/kubevirtci/golang:v20240607-febc467
+      name: ""
+      resources:
+        requests:
+          memory: 8Gi
+      securityContext:
+        privileged: true
+    nodeSelector:
+      type: bare-metal-external
+- annotations:
+    testgrid-create-test-group: "false"
   cluster: kubevirt-prow-control-plane
   cron: 2 15 */7 * *
   decorate: true
